# Analysis options untuk optimasi code
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance rules
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    
    # Memory optimization
    avoid_print: true
    avoid_relative_lib_imports: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_this: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
