package ticket

import "time"

// Ticket represents the persisted ticket entity in local database.
type Ticket struct {
	ID           string    `gorm:"type:char(36);primaryKey;default:(UUID())"` // Local identifier, use UUID generated by DB
	InvGateID    string    `gorm:"size:100;not null;index"`                   // ID dari InvGate Armmada
	SourceID     int       `gorm:"not null"`
	CreatorID    int       `gorm:"not null"`
	CustomerID   int       `gorm:"not null"`
	CategoryID   int       `gorm:"not null"`
	TypeID       int       `gorm:"not null"`
	PriorityID   int       `gorm:"not null"`
	Title        string    `gorm:"size:255;not null"`
	Description  string    `gorm:"type:text;not null"`
	CreatorEmail string    `gorm:"size:190;not null;index"`    // Email user yang membuat ticket
	CreatedBy    string    `gorm:"size:190;column:created_by"` // Email of user who created this record
	UpdatedBy    string    `gorm:"size:190;column:updated_by"` // Email of user who last updated this record
	CreatedAt    time.Time `gorm:"autoCreateTime"`
	UpdatedAt    time.Time `gorm:"autoUpdateTime"`
}

func (Ticket) TableName() string {
	return "tickets"
}
