package user

import "time"

// User represents the persisted user entity.
// This model is used by GORM for auto migration.
// When the application starts, GORM will automatically create/update the users table
// based on this struct definition.
type User struct {
	ID            string    `gorm:"type:char(36);primaryKey;default:(UUID())"` // Local identifier, use UUID generated by DB
	Name          string    `gorm:"size:100;not null"`
	LastName      string    `gorm:"size:100;not null;column:last_name"` // Explicit column name to match migration
	Email         string    `gorm:"size:190;not null;uniqueIndex"`
	Password      string    `gorm:"size:255;not null"`
	InvGateUserID int       `gorm:"not null;column:invgate_user_id"`
	CreatedBy     string    `gorm:"size:190;column:created_by"` // Email of user who created this record
	UpdatedBy     string    `gorm:"size:190;column:updated_by"` // Email of user who last updated this record
	CreatedAt     time.Time `gorm:"autoCreateTime"`
	UpdatedAt     time.Time `gorm:"autoUpdateTime"`
}

// TableName specifies the table name for GORM
func (User) TableName() string {
	return "users"
}
